---
title: "test"
author: "Karim Mané, Carmen Tamayo"
output: html_document
params:
    DISEASE_NAME: "ebola"
    DATA: "/Users/karimmane/Documents/Karim/LSHTM/TRACE_dev/Packages/On_trace_github/episoap/inst/extdata/Marburg_EqGuinea_linelist.csv"
    ACCOUNT_FOR_DELAY: FALSE
    EPIDIST: NULL
    OUTDIR: "/Users/karimmane/Documents/Karim/LSHTM/TRACE_dev/Packages/On_trace_github/episoap"
    DATE_VARIABLE_NAME: NULL
    CASES_STATUS: NULL
    DEATH_OUTCOME: NULL
    DIAGNOSIS_STATUS: NULL
    DIAGNOSIS_OUTCOME: NULL
    TYPE: NULL
    VALUES: NULL
    DISTRIBUTION: NULL
    TOTAL_CASES: NULL
    TOTAL_DEATHS: NULL
    DEATH_IN_CONFIRMED: NULL
    INTERVAL: 1
    SHAPE: NULL
    SCALE: NULL
    MEANLOG: NULL
    SDLOG: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("episoap")
library("formattable")
library("kableExtra")
```

---
    date: `r format(Sys.Date(), "%d/%m/%Y")`
---

```{r echo=FALSE, eval=TRUE, include=FALSE}
# get the user parameters
disease            <- params[["DISEASE_NAME"]]
data               <- params[["DATA"]]
account_for_delay  <- params[["ACCOUNT_FOR_DELAY"]]
epidist            <- params[["EPIDIST"]]
date_variable_name <- params[["DATE_VARIABLE_NAME"]]
cases_status       <- params[["CASES_STATUS"]]
death_outcome      <- params[["DEATH_OUTCOME"]]
diagnosis_status   <- params[["DIAGNOSIS_STATUS"]]
diagnosis_outcome  <- params[["DIAGNOSIS_OUTCOME"]]
distribution       <- params[["DISTRIBUTION"]]
type               <- params[["TYPE"]]
values             <- params[["VALUES"]]
total_cases        <- params[["TOTAL_CASES"]]
total_deaths       <- params[["TOTAL_DEATHS"]]
death_in_confirmed <- params[["DEATH_IN_CONFIRMED"]]
interval           <- params[["INTERVAL"]]
shape              <- params[["SHAPE"]]
scale              <- params[["SCALE"]]
meanlog            <- params[["MEANLOG"]]
sdlog              <- params[["SDLOG"]]
run_severity       <- TRUE
```

# severity

```{r echo=FALSE, eval=run_severity}
cfr <- get_severity(
  disease_name       = disease,
  data               = data,
  account_for_delay  = account_for_delay,
  epidist            = epidist,
  values             = values,
  type               = type,
  interval           = interval,
  distribution       = distribution,
  shape              = shape,
  scale              = scale,
  meanlog            = meanlog,
  sdlog              = sdlog,
  date_variable_name = date_variable_name,
  cases_status       = cases_status,
  death_outcome      = death_outcome,
  diagnosis_status   = diagnosis_status,
  diagnosis_outcome  = diagnosis_outcome,
  total_cases        = total_cases,
  total_deaths       = total_deaths,
  death_in_confirmed = death_in_confirmed
)
```

```{r echo=FALSE, eval=TRUE, results='asis'}
test <- reformat_cfr(cfr)
print_cfr(test)

# if (inherits(test, "list")) {
#   for (res in names(test)) {
#     # header_temp = 3
#     # names(header_temp) = get("res")
#       kable_out <- knitr::kable(test[[res]], format = "html", escape = FALSE,
#                    align = rep("c", ncol(test[[res]])), booktabs = TRUE) %>%
#       kableExtra::kable_styling("responsive", full_width = FALSE) %>%
#       kableExtra::footnote(general = "Estimated CFR (c.f. {cfr} package)",
#                            footnote_as_chunk = TRUE)
#       # add_header_above(header_temp))
#       readr::write_file(kable_out,
#                       "test.html",
#                         append = TRUE)
#   }
# }

# print_cfr(test)
# knitr::kable(test, format = "html", escape = FALSE, booktabs = TRUE,
#            align = rep("c", length(cfr))) %>%
# kableExtra::kable_styling("responsive", full_width = FALSE) %>%
# kableExtra::footnote(general = "Estimated CFR (c.f. {cfr} package)",
#                      footnote_as_chunk = TRUE)
```

# Transmissibility

```{r}

```


